spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: gabriel
    password: gbr123
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update